### PR TITLE
实际使用中遇到的问题的一些修改，经过测试。

### PR DESCRIPTION
**Pull request by BruceQiu1996**
1.增加了对于wechaty内部发送数据的实现（结构存在问题，其他部分已经有实现，但是需要重构，不然在使用发送消息的时候很容易报错，进行不下去.
2.获取发送的图片消息时，提示使用messageStream api，使用另外一个grcp的方法，
老代码并没有实现，提供了实现，并且测试使用没问题。

### CODE REVIEW

**Comment by huan** [comment]
Awesome, thank you very much for the contribution!

Please sign the CLA by clicking the `[CLA | not signed yet]` button above, then we will be able to review this PR.

**Review by echofool — APPROVED** [review]
LGTM

**Review by Jesn — COMMENTED** [review]
very good

**Comment by Jesn** [comment]
nuget version  updated to   0.1.7

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited BruceQiu1996 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Comment by BruceQiu1996** [comment]
WOW that's great.

**Pull request merged**
